# .goreleaser.yaml
# 详情参考: https://goreleaser.com

version: 2

project_name: ncmm

# 构建输出目录
dist: ./dist

before:
  hooks:
    - go mod tidy

# 编译配置
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: ncmm
    ldflags:
      - -s -w -X "main.Version={{.Version}}" -X "main.Commit={{.FullCommit}}" -X "main.BuildTime={{.CommitDate}}"
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm

# 打包配置
archives:
  - formats: [ 'tar.gz' ]
    # 归档文件名模板，例如 ncmm_Windows_x86_64.zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Windows 平台使用 zip 格式
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md
      - src: config/config.yaml
        dst: config.yaml

# 发布日志配置
changelog:
  # 优先使用 GitHub 的自动 Release Notes 生成机制，能完美展示贡献者头像
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^typo:'
      - '(?i)merge'

# 远程发布配置
release:
  github:
    owner: 3899
    name: ncmm
